# Generated by scripts/update-tap-formula.sh on each release. Do not edit
# in the tap repo.
#
# This is a formula, not a cask, on purpose: Homebrew quarantines cask
# downloads, and Gatekeeper kills quarantined binaries that are not
# notarized. Formula downloads are not quarantined.
class KubectlMole < Formula
  desc "Watch Kubernetes workloads until they settle, then explain what broke"
  homepage "https://github.com/justin-tahara/kubectl-mole"
  version "__VERSION__"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/justin-tahara/kubectl-mole/releases/download/v#{version}/kubectl-mole_v#{version}_darwin_arm64.tar.gz"
      sha256 "__SHA_DARWIN_ARM64__"
    else
      url "https://github.com/justin-tahara/kubectl-mole/releases/download/v#{version}/kubectl-mole_v#{version}_darwin_amd64.tar.gz"
      sha256 "__SHA_DARWIN_AMD64__"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/justin-tahara/kubectl-mole/releases/download/v#{version}/kubectl-mole_v#{version}_linux_arm64.tar.gz"
      sha256 "__SHA_LINUX_ARM64__"
    else
      url "https://github.com/justin-tahara/kubectl-mole/releases/download/v#{version}/kubectl-mole_v#{version}_linux_amd64.tar.gz"
      sha256 "__SHA_LINUX_AMD64__"
    end
  end

  def install
    bin.install "kubectl-mole"
  end

  def caveats
    <<~EOS
      kubectl-mole needs read access to workloads, pods, and events.
      A minimal ClusterRole ships with the repo: deploy/rbac.yaml
    EOS
  end

  test do
    assert_match "kubectl-mole version v#{version}", shell_output("#{bin}/kubectl-mole --version")
  end
end
